<section class="section education" id="education" aria-labelledby="education-heading">
	<div class="shell education-grid"><div><p class="eyebrow">04 — Path so far</p><h2 class="display section-title" id="education-heading">Learning the systems behind the screen.</h2><p class="section-lede">Building a foundation in information engineering while making room for the questions that lead to the next project.</p></div>
		<ol class="timeline"><li><span class="timeline-dot" aria-hidden="true"></span><div class="timeline-card glass-card"><div class="timeline-top"><span class="now">Now</span><span>Hong Kong</span></div><h3 class="display">The Chinese University of Hong Kong</h3><p>Information Engineering student in the Faculty of Information Engineering.</p><div class="focus"><span>Computer science</span><span>Game programming</span><span>Hardware curiosity</span></div></div></li><li class="next"><span class="timeline-dot" aria-hidden="true"></span><p>Next: keep learning, make indie games, and understand hardware more deeply.</p></li></ol>
	</div>
</section>

<style>
	.education { background: linear-gradient(110deg, rgba(82,225,207,.055), transparent 50%); } .education-grid { display: grid; grid-template-columns: .85fr 1.15fr; gap: 5rem; } .timeline { border-left: 1px solid rgba(82,225,207,.3); list-style: none; margin: .5rem 0; padding: 0 0 0 2rem; } .timeline li { position: relative; } .timeline-dot { background: var(--color-aqua); border-radius: 50%; box-shadow: 0 0 0 .32rem rgba(82,225,207,.12); height: .65rem; left: -2.35rem; position: absolute; top: 1.5rem; width: .65rem; } .timeline-card { border-radius: 1.25rem; padding: 1.5rem; } .timeline-top { color: var(--color-muted); display: flex; font-size: .74rem; font-weight: 700; justify-content: space-between; letter-spacing: .08em; text-transform: uppercase; } .now { color: var(--color-aqua); } .timeline-card h3 { font-size: 1.42rem; margin: 1.5rem 0 .55rem; } .timeline-card p { color: #b6c1de; line-height: 1.65; margin: 0; } .focus { display: flex; flex-wrap: wrap; gap: .5rem; margin-top: 1.25rem; } .focus span { border: 1px solid var(--color-line); border-radius: 999px; color: var(--color-muted); font-size: .72rem; padding: .36rem .6rem; } .next { margin-top: 1.6rem; min-height: 3rem; } .next .timeline-dot { background: #4e5c81; box-shadow: none; top: .28rem; } .next p { color: var(--color-muted); font-size: .9rem; line-height: 1.6; margin: 0; } @media (max-width: 800px) { .education-grid { grid-template-columns: 1fr; gap: 2rem; } }
</style>
