<script>
	const projects = [
		{ number: '01', tag: 'Pascal', icon: '✦', title: 'Minesweeper', description: 'A classic grid puzzle rebuilt in Pascal — a focused exercise in state, rules, and careful logic.', color: 'mint' },
		{ number: '02', tag: 'Automation', icon: '⌁', title: 'Telegram & Discord bots', description: 'Bots that bring small automations and helpful interactions to the conversations where communities already gather.', color: 'violet' },
		{ number: '03', tag: 'Simulation', icon: '↕', title: 'Elevator Simulator', description: 'An exploration of movement, scheduling, and the unexpected detail hiding in everyday systems.', color: 'blue' },
		{ number: '04', tag: 'Rust · Godot', icon: '◈', title: 'Monopoly-like game', description: 'A board-game experiment written in Rust with the Godot engine, combining systems thinking with play.', color: 'peach' }
	];
</script>

<section class="section" id="projects" aria-labelledby="projects-heading">
	<div class="shell"><div class="project-top"><div><p class="eyebrow">03 — Selected work</p><h2 class="display section-title" id="projects-heading">Small experiments,<br />serious curiosity.</h2></div><p>Four projects spanning classic game logic, community tools, simulations, and a multiplayer-inspired board game.</p></div>
		<div class="project-grid">{#each projects as project}<article class={`project-card ${project.color}`}><div class="card-meta"><span>{project.number}</span><span>{project.tag}</span></div><div class="project-icon" aria-hidden="true">{project.icon}</div><div class="card-bottom"><h3 class="display">{project.title}</h3><p>{project.description}</p><span class="explore">Explore project <b aria-hidden="true">↗</b></span></div></article>{/each}</div>
	</div>
</section>

<style>
	.project-top { display: flex; justify-content: space-between; gap: 2rem; align-items: end; } .project-top > p { color: var(--color-muted); line-height: 1.7; max-width: 330px; margin: 0 0 .25rem; } .project-grid { display: grid; grid-template-columns: repeat(2,1fr); gap: 1.2rem; margin-top: 3rem; } .project-card { border: 1px solid var(--color-line); border-radius: 1.35rem; display: flex; flex-direction: column; min-height: 355px; overflow: hidden; padding: 1.45rem; position: relative; transition: transform 220ms ease, border-color 220ms ease, box-shadow 220ms ease; } .project-card::before { content: ''; position: absolute; width: 11rem; height: 11rem; border-radius: 50%; right: -3rem; top: -3rem; filter: blur(5px); opacity: .4; } .project-card:hover { border-color: rgba(197,213,255,.32); box-shadow: 0 22px 50px rgba(0,0,0,.22); transform: translateY(-5px); } .mint { background: linear-gradient(135deg,#0e2d30,#101b2b); } .mint::before { background:#52e1cf; } .violet { background: linear-gradient(135deg,#251a43,#15142d); } .violet::before { background:#a78bfa; } .blue { background: linear-gradient(135deg,#122d50,#101a30); } .blue::before { background:#65a5ff; } .peach { background: linear-gradient(135deg,#3e2430,#1e1727); } .peach::before { background:#ffad7d; } .card-meta { display: flex; justify-content: space-between; color: rgba(233,240,255,.6); font-size: .7rem; font-weight: 700; letter-spacing: .1em; position: relative; text-transform: uppercase; z-index: 1; } .project-icon { align-items: center; background: rgba(255,255,255,.09); border: 1px solid rgba(255,255,255,.12); border-radius: 1rem; display: flex; font-family: var(--font-display); font-size: 2.3rem; height: 4.3rem; justify-content: center; margin-top: auto; width: 4.3rem; } .card-bottom { margin-top: 1.4rem; } .card-bottom h3 { font-size: clamp(1.5rem,3vw,2rem); margin: 0; } .card-bottom p { color: #c0cae4; font-size: .9rem; line-height: 1.6; margin: .6rem 0 1rem; max-width: 450px; } .explore { color: #fff; font-size: .8rem; font-weight: 750; } .explore b { color: var(--color-aqua); font-size: 1rem; margin-left: .15rem; } @media (max-width: 700px) { .project-top { align-items: start; flex-direction: column; } .project-grid { grid-template-columns: 1fr; } .project-card { min-height: 320px; } }
</style>
